version: "3"
services:
  app:
    build: .
    command: /bin/sh -c "bundle exec reveal-ck serve -h 0.0.0.0"
    ports:
      - 10000:10000
    stdin_open: true
    tty: true
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/app
volumes:
  bundle_cache:
