name: Release

on:
  push:
    branches: [main]

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7.2
      volumes:
        - bundle_cache:/usr/local/bundle
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: /usr/local/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: bundle install
        run: |
          bundle install
      - name: Remove slides
        run: |
          rm -rf slides
      - name: Clone gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/wat-aro/recommendation-of-hook.git --branch gh-pages --single-branch ./slides
      - name: Run build
        run: |
          bundle exec reveal-ck generate
      - name: Release slides
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email ${{secrets.EMAIL}}
          git config --global user.name ${{secrets.NAME}}
          cd slides && git add . && git commit -m 'Release!' && git push origin gh-pages:gh-pages -f || true
